// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	notes "github.com/Dorrrke/notes-g2/internal/domain/notes"
	mock "github.com/stretchr/testify/mock"

	users "github.com/Dorrrke/notes-g2/internal/domain/users"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// Close provides a mock function with no fields
func (_m *Repository) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetNote provides a mock function with given fields: nid
func (_m *Repository) GetNote(nid string) (notes.Note, error) {
	ret := _m.Called(nid)

	if len(ret) == 0 {
		panic("no return value specified for GetNote")
	}

	var r0 notes.Note
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (notes.Note, error)); ok {
		return rf(nid)
	}
	if rf, ok := ret.Get(0).(func(string) notes.Note); ok {
		r0 = rf(nid)
	} else {
		r0 = ret.Get(0).(notes.Note)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(nid)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetNotes provides a mock function with no fields
func (_m *Repository) GetNotes() ([]notes.Note, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetNotes")
	}

	var r0 []notes.Note
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]notes.Note, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []notes.Note); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]notes.Note)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUser provides a mock function with given fields: login
func (_m *Repository) GetUser(login string) (users.User, error) {
	ret := _m.Called(login)

	if len(ret) == 0 {
		panic("no return value specified for GetUser")
	}

	var r0 users.User
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (users.User, error)); ok {
		return rf(login)
	}
	if rf, ok := ret.Get(0).(func(string) users.User); ok {
		r0 = rf(login)
	} else {
		r0 = ret.Get(0).(users.User)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(login)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SaveNotes provides a mock function with given fields: tasks
func (_m *Repository) SaveNotes(tasks []notes.Note) error {
	ret := _m.Called(tasks)

	if len(ret) == 0 {
		panic("no return value specified for SaveNotes")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func([]notes.Note) error); ok {
		r0 = rf(tasks)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SaveUser provides a mock function with given fields: user
func (_m *Repository) SaveUser(user users.User) error {
	ret := _m.Called(user)

	if len(ret) == 0 {
		panic("no return value specified for SaveUser")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(users.User) error); ok {
		r0 = rf(user)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
